name: autofix.ci

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  autofix:
    uses: heyongqi02/workflows/.github/workflows/autofix.yml@vp
    permissions:
      contents: read
    with:
      command: vpx automd && vp check --fix
